name: Monorepo CI
on:
  push:
    branches: [main]  # מריץ על כל push ל-main
  pull_request:
    branches: [main]  # וגם על pull request ל-main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - name: :inbox_tray: Checkout code
        uses: actions/checkout@v3
      - name: :large_green_circle: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: :package: Install server dependencies
        working-directory: ./packages/server
        run: yarn install
      - name: :hammer_and_wrench: Build server
        working-directory: ./packages/server
        run: yarn build
      - name: :white_check_mark: Test server
        working-directory: ./packages/server
        run: yarn test || echo "No server tests"
      - name: :package: Install client dependencies
        working-directory: ./packages/client
        run: yarn install
      - name: :hammer_and_wrench: Build client
        working-directory: ./packages/client
        run: yarn build
      - name: :white_check_mark: Test client
        working-directory: ./packages/client
        run: yarn test || echo "No client tests"